# Generated by Django 6.0.3 on 2026-04-04 22:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artigo',
            options={'ordering': ['-data_publicacao']},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.AddField(
            model_name='artigo',
            name='data_publicacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comentario',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto_comentario',
            field=models.TextField(verbose_name='O teu comentário'),
        ),
    ]
